- name: Instalando o pip
  apt:
    name: 
      - python-pip

- name: Instalando dependencias do modulos do k8s
  pip:
    name:
      - openshift
      - PyYAML

- name: Copiando o arquivo de deployment da app v1
  template:
    src: app-v1.yml.j2
    dest: "{{ destFileV1 }}"
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v1

- name: Copiando o arquivo de deployment da app v2
  template:
    src: app-v2.yml.j2
    dest: "{{ destFileV2 }}"
    owner: root
    group: root
    mode: 0644
  register: copiando_deploy_app_v2

  # k8s:
  #   state: present
  #   namespace: default
  #   src: "{{ destFileV2 }}"
# Como se fosse: 
- name: Deploy da app-v2
  shell: kubectl create -f {{ destFileV2 }}
  
# Dentro do arquivo já terá o número de réplicas
- name: Scale down da app-v1
  k8s:
    state: present
    namespace: default
    src: "{{ destFileV1 }}"

- name: Dentro de 02 minutos o app-v1 sera removido. Pressione control+c para cancelar
  pause:
    minutes: 2

- name: Removendo o app-v1
  k8s:
    state: absent
    namespace: default
    src: "{{ destFileV1 }}"